reset;
model AD2b.mod;
data AD2.dat;

option solver cplex;

option show_stats 1;#To display solver statiscs (Useful later with Integer variables)
option cplex_options 'mipdisplay=4 mipinterval=2';#How to display solver statistics(Useful later with Integer variables

solve;
show>AD2b.txt;
display max_dist>AD2b.txt;
display X>AD2b.txt;
display Y>AD2b.txt;
display _total_solve_time>AD2b.txt;
expand>AD2b.txt;
close AD2b.txt;


